### ISSUE TITLE
Failing during uninstall

### ISSUE THREAD

**Issue by marcosfreitas** [EvanHerman/wp-rest-api-controller#11]
I installed this plugin (v 2.0.0) into WordPress v5.1.1 but when I tried to remove this using the panel it throws this exception:

```
[03-May-2019 13:29:09 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method wpdb::execute() in /var/www/html/wp-content/plugins/wp-rest-api-controller/uninstall.php:35
Stack trace:
#0 /var/www/html/wp-admin/includes/plugin.php(1114): include()
#1 /var/www/html/wp-admin/includes/plugin.php(917): uninstall_plugin('wp-rest-api-con...')
#2 /var/www/html/wp-admin/includes/ajax-actions.php(4296): delete_plugins(Array)
#3 /var/www/html/wp-includes/class-wp-hook.php(286): wp_ajax_delete_plugin('')
#4 /var/www/html/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array)
#5 /var/www/html/wp-includes/plugin.php(465): WP_Hook->do_action(Array)
#6 /var/www/html/wp-admin/admin-ajax.php(167): do_action('wp_ajax_delete-...')
#7 {main}
```

I solved this changing `execute` to `query`. But I don't know if it is the best approach.

**Comment by kpu23** [comment]
Hey @marcosfreitas,

Thanks for letting us know. It should be `query`, probably with a `prepare` statement in there. We'll fix this soon.

**Comment by 4n70w4** [comment]
The same error!

**Comment by 4n70w4** [comment]
The same error! @kpu23 can you suggest a workaround?

**Comment by kpu23** [comment]
We'll have a fix for this today, within the next few hours.

**Comment by kpu23** [comment]
The fix has been released.
